#!/bin/bash

# Inspiration: https://github.com/alrra/dotfiles/blob/master/shell/bash_exports
# and original Ubuntu bashrc

# Make nano the default editor
export EDITOR='nano'

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the
# history file (default value is 500)
export HISTFILESIZE=10000

# Don't add certain commands to the history file
export HISTIGNORE='&:[bf]g:c:clear:history:exit:q:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Prefer US English and use UTF-8 encoding
export LANG='en_US'
export LC_ALL='en_US.UTF-8'

# Don't clear the screen after quitting a man page
export MANPAGER='less -X'

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
# Call set_prompts to insert Git Branch info (and colour)
export PROMPT_COMMAND="history -a; set_prompts; $PROMPT_COMMAND"

# Always enable colored `grep` output.
export GREP_OPTIONS='--color=auto';
