#!/bin/bash

# Shell Options
# http://ss64.com/bash/shopt.html
# From: https://github.com/alrra/dotfiles/blob/master/shell/bash_options

source "$(dirname $(readlink $BASH_SOURCE))/utils/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Autocorrect typos in path names when using the `cd` command
shopt -s cdspell

# Check the window size after each command and, if necessary, update
# the values of `LINES` and `COLUMNS`
shopt -s checkwinsize

# Save all lines of a multiple-line command in the same history entry
shopt -s cmdhist

# Include filenames beginning with a "." in the filename expansion
shopt -s dotglob

# Use extended pattern matching features
shopt -s extglob

# Append to the history file, rather then overwriting it
shopt -s histappend

# Attempt hostname completion
shopt -s hostcomplete

# Do not attempt to search the PATH for possible completions when
# completion is attempted on an empty line
shopt -s no_empty_cmd_completion

# Match filenames in a case-insensitive# fashion when performing
# filename expansion
shopt -s nocaseglob


# OSX Preferences
# ---------------------------

declare OS="$(get_os)"

if [ "$OS" == 'osx' ]; then

    # Disable New Mail check
    unset MAILCHECK
    shopt -u mailwarn

fi

unset OS
